In [24]:
import cv2
import numpy as np

In [25]:
for i in range(300,1100, 4):
    I = cv2.imread('pedestrian/input/in%06d.jpg' % i)
    cv2.imshow("I",I)
    cv2.waitKey(10)
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [ ]:
i_prev = cv2.cvtColor(cv2.imread('pedestrian/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')

for i in range(300,1100, 1):
    I = cv2.imread('pedestrian/input/in%06d.jpg' % i)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    Res2 = 1 * (Res > T) * 255
    cv2.imshow("I",np.uint8(Res2))
    i_prev = i_gray
    cv2.waitKey(10)
    
cv2.destroyAllWindows()

In [ ]:
i_prev = cv2.cvtColor(cv2.imread('pedestrian/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')

for i in range(300,1100, 1):
    I = cv2.imread('pedestrian/input/in%06d.jpg' % i)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    Res2 = 1 * (Res > T) * 255
    Res2 = cv2.medianBlur(Res, 3)
    kernel = np.ones((3, 3), np.uint8)
    Res2 = cv2.dilate(Res2, kernel)
    
    cv2.imshow("I",np.uint8(Res2))
    i_prev = i_gray
    cv2.waitKey(10)
    
cv2.destroyAllWindows()

In [39]:
i_prev = cv2.cvtColor(cv2.imread('pedestrian/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')

for i in range(300,1100, 1):
    I = cv2.imread('pedestrian/input/in%06d.jpg' % i)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    print(thresh)
    Res2 = 1 * (Res > T) * 255
    Res2 = cv2.medianBlur(thresh, 3)
    kernel = np.ones((5, 5), np.uint8)
    kernel2 = np.ones((3, 3), np.uint8)
    Res2 = cv2.erode(Res2, kernel2)
    Res2 = cv2.dilate(Res2, kernel)
    Res2 = np.uint8(Res2)
    retval, labels, stats, centroids = cv2.connectedComponentsWithStats(Res2)
    cv2.imshow("I", np.uint8(labels/retval*255))
    I_VIS = I # copy of the input image
    if (stats.shape[0] > 1): # are there any objects
        tab = stats[1:,4] # 4 columns without first element
        pi = np.argmax( tab )# finding the index of the largest item
        pi = pi + 1 # increment because we want the index in stats, not in tab
        # drawing a bbox
        cv2.rectangle(I_VIS,(stats[pi,0],stats[pi,1]),(stats[pi,0]+stats[pi,2],
        stats[pi,1]+stats[pi,3]),(255,0,0),2)
        cv2.putText(I_VIS,"%f" % stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))
        cv2.putText(I_VIS,"%d" %pi,(int(centroids[pi,0]),int(centroids[pi,1])),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0))
    cv2.imshow("I",I_VIS)
    i_prev = i_gray
    
    cv2.waitKey(10)
    
    
cv2.destroyAllWindows()

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0 255 ...   0   0   0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0 255]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[  0   0   0 ..

In [48]:
i_prev = cv2.cvtColor(cv2.imread('pedestrian/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')
TP = 0
TN = 0
FP = 0
FN = 0
f = open('pedestrian/temporalROI.txt','r') # open file
line = f.readline() # read line
roi_start, roi_end = line.split() # split line
roi_start = int(roi_start) # conversion to int
roi_end = int(roi_end) # conversion to int

for i in range(roi_start,roi_end, 1):
    
    I = cv2.imread('pedestrian/input/in%06d.jpg' % i)
    I_mask = cv2.imread('pedestrian/groundtruth/gt%06d.png' % i)
    I_mask = cv2.cvtColor(I_mask, cv2.COLOR_BGR2GRAY)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    Res2 = 1 * (Res > T) * 255
    Res2 = cv2.medianBlur(thresh, 3)
    kernel = np.ones((5, 5), np.uint8)
    kernel2 = np.ones((3, 3), np.uint8)
    Res2 = cv2.erode(Res2, kernel2)
    Res2 = cv2.dilate(Res2, kernel)
    Res2 = np.uint8(Res2)
    retval, labels, stats, centroids = cv2.connectedComponentsWithStats(Res2)
    cv2.imshow("I", np.uint8(labels/retval*255))
    I_VIS = I # copy of the input image
    if (stats.shape[0] > 1): # are there any objects
        tab = stats[1:,4] # 4 columns without first element
        pi = np.argmax( tab )# finding the index of the largest item
        pi = pi + 1 # increment because we want the index in stats, not in tab
        # drawing a bbox
        cv2.rectangle(I_VIS,(stats[pi,0],stats[pi,1]),(stats[pi,0]+stats[pi,2],
        stats[pi,1]+stats[pi,3]),(255,0,0),2)
        cv2.putText(I_VIS,"%f" % stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))
        cv2.putText(I_VIS,"%d" %pi,(int(centroids[pi,0]),int(centroids[pi,1])),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0))
    cv2.imshow("I",I_VIS)
    TP_M = np.logical_and((Res2 == 255),(I_mask == 255)) # logical product of the matrix elements
    TP_S = np.sum(TP_M) # sum of the elements in the matrix
    TP = TP + TP_S

    TN_M = np.logical_and((Res2 == 0),(I_mask == 0)) # logical product of the matrix elements
    TN_S = np.sum(TN_M) # sum of the elements in the matrix
    TN = TN + TN_S

    FP_M = np.logical_and((Res2 == 255),(I_mask == 0)) # logical product of the matrix elements
    FP_S = np.sum(FP_M) # sum of the elements in the matrix
    FP = FP + FP_S

    FN_M = np.logical_and((Res2 == 0),(I_mask == 255)) # logical product of the matrix elements
    FN_S = np.sum(FN_M) # sum of the elements in the matrix
    FN = FN + FN_S
    i_prev = i_gray
    
    cv2.waitKey(10)
P = TP/(TP+FP)
R = (TP/(TP+FN))
F1 = ((2*P*R)/(P + R))
print(P)
print("R:", R)
print(F1)
cv2.destroyAllWindows()

0.5228264600598245
R: 0.7628633012452636
0.6204375756943881


In [52]:
i_prev = cv2.cvtColor(cv2.imread('highway/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')
TP = 0
TN = 0
FP = 0
FN = 0
f = open('highway/temporalROI.txt','r') # open file
line = f.readline() # read line
roi_start, roi_end = line.split() # split line
roi_start = int(roi_start) # conversion to int
roi_end = int(roi_end) # conversion to int

for i in range(roi_start,roi_end, 1):
    
    I = cv2.imread('highway/input/in%06d.jpg' % i)
    I_mask = cv2.imread('highway/groundtruth/gt%06d.png' % i)
    I_mask = cv2.cvtColor(I_mask, cv2.COLOR_BGR2GRAY)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    Res2 = 1 * (Res > T) * 255
    Res2 = cv2.medianBlur(thresh, 3)
    kernel = np.ones((5, 5), np.uint8)
    kernel2 = np.ones((3, 3), np.uint8)
    Res2 = cv2.erode(Res2, kernel2)
    Res2 = cv2.dilate(Res2, kernel)
    Res2 = np.uint8(Res2)
    retval, labels, stats, centroids = cv2.connectedComponentsWithStats(Res2)
    cv2.imshow("I", np.uint8(labels/retval*255))
    I_VIS = I # copy of the input image
    if (stats.shape[0] > 1): # are there any objects
        tab = stats[1:,4] # 4 columns without first element
        pi = np.argmax( tab )# finding the index of the largest item
        pi = pi + 1 # increment because we want the index in stats, not in tab
        # drawing a bbox
        cv2.rectangle(I_VIS,(stats[pi,0],stats[pi,1]),(stats[pi,0]+stats[pi,2],
        stats[pi,1]+stats[pi,3]),(255,0,0),2)
        cv2.putText(I_VIS,"%f" % stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))
        cv2.putText(I_VIS,"%d" %pi,(int(centroids[pi,0]),int(centroids[pi,1])),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0))
    cv2.imshow("I",I_VIS)
    TP_M = np.logical_and((Res2 == 255),(I_mask == 255)) # logical product of the matrix elements
    TP_S = np.sum(TP_M) # sum of the elements in the matrix
    TP = TP + TP_S

    TN_M = np.logical_and((Res2 == 0),(I_mask == 0)) # logical product of the matrix elements
    TN_S = np.sum(TN_M) # sum of the elements in the matrix
    TN = TN + TN_S

    FP_M = np.logical_and((Res2 == 255),(I_mask == 0)) # logical product of the matrix elements
    FP_S = np.sum(FP_M) # sum of the elements in the matrix
    FP = FP + FP_S

    FN_M = np.logical_and((Res2 == 0),(I_mask == 255)) # logical product of the matrix elements
    FN_S = np.sum(FN_M) # sum of the elements in the matrix
    FN = FN + FN_S
    i_prev = i_gray
    
    cv2.waitKey(10)
P = TP/(TP+FP)
R = (TP/(TP+FN))
F1 = ((2*P*R)/(P + R))
print("P:",P)
print("R:", R)
print("F1:",F1)
cv2.destroyAllWindows()

P: 0.8674384611607611
R: 0.8008598841435873
F1: 0.8328206611991394


In [51]:
i_prev = cv2.cvtColor(cv2.imread('office/input/in%06d.jpg' % 1), cv2.COLOR_BGR2GRAY).astype('int')
TP = 0
TN = 0
FP = 0
FN = 0
f = open('office/temporalROI.txt','r') # open file
line = f.readline() # read line
roi_start, roi_end = line.split() # split line
roi_start = int(roi_start) # conversion to int
roi_end = int(roi_end) # conversion to int

for i in range(roi_start,roi_end, 1):
    
    I = cv2.imread('office/input/in%06d.jpg' % i)
    I_mask = cv2.imread('office/groundtruth/gt%06d.png' % i)
    I_mask = cv2.cvtColor(I_mask, cv2.COLOR_BGR2GRAY)
    i_gray = cv2.cvtColor(I, cv2.COLOR_BGR2GRAY)
    i_gray = i_gray.astype('int')
    Res = np.uint8(cv2.absdiff(i_prev, i_gray))
    (T, thresh) = cv2.threshold(Res,10,255,cv2.THRESH_BINARY)
    Res2 = 1 * (Res > T) * 255
    Res2 = cv2.medianBlur(thresh, 3)
    kernel = np.ones((5, 5), np.uint8)
    kernel2 = np.ones((3, 3), np.uint8)
    Res2 = cv2.erode(Res2, kernel2)
    Res2 = cv2.dilate(Res2, kernel)
    Res2 = np.uint8(Res2)
    retval, labels, stats, centroids = cv2.connectedComponentsWithStats(Res2)
    cv2.imshow("I", np.uint8(labels/retval*255))
    I_VIS = I # copy of the input image
    if (stats.shape[0] > 1): # are there any objects
        tab = stats[1:,4] # 4 columns without first element
        pi = np.argmax( tab )# finding the index of the largest item
        pi = pi + 1 # increment because we want the index in stats, not in tab
        # drawing a bbox
        cv2.rectangle(I_VIS,(stats[pi,0],stats[pi,1]),(stats[pi,0]+stats[pi,2],
        stats[pi,1]+stats[pi,3]),(255,0,0),2)
        cv2.putText(I_VIS,"%f" % stats[pi,4],(stats[pi,0],stats[pi,1]),cv2.FONT_HERSHEY_SIMPLEX,0.5,(255,0,0))
        cv2.putText(I_VIS,"%d" %pi,(int(centroids[pi,0]),int(centroids[pi,1])),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0))
    cv2.imshow("I",I_VIS)
    TP_M = np.logical_and((Res2 == 255),(I_mask == 255)) # logical product of the matrix elements
    TP_S = np.sum(TP_M) # sum of the elements in the matrix
    TP = TP + TP_S

    TN_M = np.logical_and((Res2 == 0),(I_mask == 0)) # logical product of the matrix elements
    TN_S = np.sum(TN_M) # sum of the elements in the matrix
    TN = TN + TN_S

    FP_M = np.logical_and((Res2 == 255),(I_mask == 0)) # logical product of the matrix elements
    FP_S = np.sum(FP_M) # sum of the elements in the matrix
    FP = FP + FP_S

    FN_M = np.logical_and((Res2 == 0),(I_mask == 255)) # logical product of the matrix elements
    FN_S = np.sum(FN_M) # sum of the elements in the matrix
    FN = FN + FN_S
    i_prev = i_gray
    
    cv2.waitKey(10)
P = TP/(TP+FP)
R = (TP/(TP+FN))
F1 = ((2*P*R)/(P + R))
print("P:",P)
print("R:", R)
print("F1:",F1)
cv2.destroyAllWindows()

P: 0.806205377797905
R: 0.11412187833180246
F1: 0.19994120878786711
